# Generated by Django 4.0.5 on 2022-07-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField()),
                ('follows', models.IntegerField()),
                ('users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('avatar', models.URLField(default='https://www.freeiconspng.com/uploads/user-icon-png-person-user-profile-icon-20.png')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('cookie', models.TextField(null=True)),
                ('has_cookie', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('token', models.TextField(null=True)),
                ('used_ids', models.TextField(null=True)),
                ('last_submit', models.DateTimeField(null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
