# Generated by Django 4.0.5 on 2022-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
