# Generated by Django 4.0.5 on 2022-07-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_account_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
