# Generated by Django 4.0.5 on 2022-07-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_account_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='used_ids',
            field=models.TextField(default=''),
        ),
    ]
