# Generated by Django 4.0.5 on 2022-07-11 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_account_used_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 19, 14, 22)),
        ),
    ]
