# Generated by Django 4.1.4 on 2022-12-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_liker_threads_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liker_threads_info',
            name='amount',
            field=models.IntegerField(max_length=200),
        ),
    ]
